name       : python-pastel
version    : 0.2.1
release    : 1
source     :
    - https://pypi.io/packages/source/p/pastel/pastel-0.2.1.tar.gz : e6581ac04e973cac858828c6202c1e1e81fee1dc7de7683f3e1ffe0bfd8a573d
license    : MIT
component  : programming.python
summary    : Bring colors to your terminal.
description: |
    Pastel is a simple library to help you colorize strings in your terminal.
build      : |
    %python3_setup
install    : |
    %python3_install
    # ...
    rm -r $installdir/usr/lib/python%python3_version%/site-packages/tests/
